name: movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  animated_rating_stars: ^1.0.1
  dropdown_button2: ^2.3.9
  flutter_xlider: ^3.5.0
  pip_view_custom_size: ^0.10.0

  path_provider: ^2.1.5
  dio: ^5.8.0+1
  permission_handler: ^11.4.0
  open_file: ^3.5.10

  lottie: ^3.1.3
  introduction_screen: ^3.1.16
  http: ^1.2.2
  flutter_native_splash: ^2.3.13
  # icon
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  icofont_flutter: ^1.4.0
  material_design_icons_flutter: ^7.0.7296
  flutter_feather_icons: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#171717"
  background_image: assets/icon/icon.png
  image: assets/icon/icon.png
  branding: assets/icon/icon.png
  # color_dark: "#121212"
  # image_dark: assets/logo/logo_1.jpg
  # branding_dark: assets/logo/logo_1.jpg

  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#4e4376"
    image_dark: assets/icon/icon.png
    icon_background_color_dark: "#171717"

  web: false


flutter:

  uses-material-design: true

  assets:
    - assets/animation/
    - assets/icon/
    - assets/images/
    - assets/lang/
    - assets/font/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/font/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/font/Urbanist-VariableFont_wght.ttf
         
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

